### ISSUE TITLE
Join request

### ISSUE THREAD

**Issue by Ayushparikh-code** [Pixisoft/Join#1]
Software: [Name of the service you wish to access the source code]

**Comment by jcs090218** [comment]
Thanks for applying the Join Request!

Can you tell me what software/service you use, so I can ad you to the team? Appreciated! 👍

**Comment by Ayushparikh-code** [comment]
> Thanks for applying the Join Request!
> 
> Can you tell me what software/service you use, so I can ad you to the team? Appreciated! 👍

Used  Web-dev and ga tools and softwares

**Comment by jcs090218** [comment]
Sorry, but the join request is only for our clients that has already purchased one of our services!

I assumed you are a potential client. Please contact us by email at pixisoft.tw@gmail.com if you are looking for outsourcing help! We apologize that we do not have the guide set up yet since we recently began our business. 😓

**Comment by Ayushparikh-code** [comment]
> Sorry, but the join request is only for our clients that has already purchased one of our services!
> 
> I assumed you are a potential client. Please contact us by email at [pixisoft.tw@gmail.com](mailto:pixisoft.tw@gmail.com) if you are looking for outsourcing help! We apologize that we do not have the guide set up yet since we recently began our business. 😓

Alright , No problem 👍🏻
